version: "3"
services:
  api:
    container_name: "api"
    command: "npm run start"
    build: .
    env_file:
      - .env
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    ports:
      - "3006:3006"
      - ${PORT}:${PORT}
    restart: on-failure
    links:
      - database
    depends_on:
      - database

  database:
    image: mysql:8.0
    container_name: "database"
    env_file:
      - .env
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
