## Criar transação [POST]
Cria uma nova transação vinculada ao usuário.

+ Request JSON Message
    + Headers
        Accept: application/json
    + Attributes
        + id: trs_1234 (string, required)
        + amount: 1000 (number, required)
        + description: Essa é uma transação (string, required)
        + payment_method (PaymentMethods): (string, required)
        + card_number: 1111222233334444 (string, required)
        + card_holder_name: João da Silva Sauro (string, required)
        + card_expiration_date: 0520 (string, required)
        + api_key: AA97B177-9383-4934-8543-0F91A7A02836 (string, required)

+ Response 201 (application/json)
    + Attributes
        + id: trs_1234 (string, required)
        + amount: 1000 (number, required)
        + description: Essa é uma transação (string, required)
        + payment_method: debit_card (string, required)
        + last_card_digits: 4444 (string, required)
        + card_holder_name: João da Silva Sauro (string, required)
        + card_expiration_date: 0520 (string, required)
        + created_at: `2019-10-18-10:05:55` (string, required)

+ Response 401 (application/json)
    + Attributes (Error401)
