## Listar resumo [/funds/resume]
## Listar resumo [GET]
Devolve os fundos disponíveis e que serão disponibilizados para saque ao usuário.

+ Response 200 (application/json)
    + Attributes
        + available: 1000 (number, required)
        + waiting: 1000 (number, required)
