version: 2

jobs:
  lint:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run lint
          command: npm run lint
  test:
    machine: true
    steps:
      - checkout
      # - run:
      #     name: Give Docker permissions
      #     command: |
      #       sudo groupadd docker
      #       sudo usermod -aG docker root
      #       sudo service docker restart
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.21.2/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - run:
          name: Build docker-compose containers
          command: |
            docker -v
            docker-compose -v
            mv .env.test.example .env
            make up-silent
            docker ps
      - run:
          name: Run migration
          command: make migrate
      - run:
          name: Run seeds
          command: make seed
      - run:
          name: Run tests
          command: make test

workflows:
  version: 2
  build_and_test:
    jobs:
      - lint
      - test
