name: Node CI

on: ["pull_request"]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x

    - name: npm install, lint
      run: |
        npm install
        npm run lint
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x

    - name: Shutdown Ubuntu MySQL (SUDO)
      run: sudo service mysql stop

    - name: Use MySQL 8.0
      uses: mirromutth/mysql-action@v1.1
      with:
        mysql version: '8.0'
        mysql database: 'psp-database'
        mysql user: 'user'
        mysql password: 'password'

    - name: npm install, codecoverage
      run: |
        mv .env.test.example .env
        npm install
        npm run migrate
        npm run seed
        npm run test
        npm run coverage

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Coveralls Finished
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        parallel-finished: true
